version: "3"
services:
  php:
    hostname: app-1
    container_name: app-1
    image: crunchgeek/php-fpm:7.2
    working_dir: /app-1
    volumes:
      - .:/app-1:delegated
      - ../nginx/infrastructure:/config:delegated
    networks:
      - php-network
    environment:
      # more info at: https://github.com/markhilton/docker-php-fpm
      - PHP_UID=9000
      - PHP_GID=9000
      - PHP_USER=php-fpm
      - PHP_HOME=/app-1
      - PHP_POOL_PATH=/config/www.conf

networks:
  php-network:
    driver: "bridge"
